import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {access,readFile,writeFile,mkdir} from 'node:fs/promises';
const exec=promisify(execFile),project=process.cwd(),out=`${project}/artifacts/prop-review/output`,instance='texture-gap-native',session='texture-gap-sweep-a-20261007';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function cli(...args){const {stdout}=await exec(process.execPath,['tools/godot-cli/dist/src/index.js',...args,'--json'],{cwd:project,windowsHide:true,timeout:600000,maxBuffer:30e6,env:{...process.env,GODMODE_SESSION_ID:session,GODMODE_PREBUILT_GENERATING:'1'}});const value=JSON.parse(stdout);assert(value.ok,value.message);return value.data;}
const action=(name,payload={})=>cli('runtime','action','--project',project,'--instance',instance,'--name',name,'--payload',JSON.stringify(payload),...(['debug_kill_admins','batch_stage'].includes(name)?['--allow-refused']:[]));
const save=(name,v)=>writeFile(`${out}/${name}.json`,JSON.stringify(v,null,2)+'\n');
function offset(stage,radius,multiplier){const n=stage.nativeSample?.viewNormal;if(!n)return[radius*.5*multiplier,radius*.35*multiplier,radius*.9*multiplier];const tangent=Math.abs(n[1])>.8?[.35,0,.3]:[0,.25,0];return n.map((v,i)=>(v+tangent[i])*radius*multiplier);}
function look(id,center,offset){const position=center.map((v,i)=>v+offset[i]),[x,y,z]=center.map((v,i)=>v-position[i]);return{id,position,yaw:Math.atan2(-x,-z),pitch:Math.atan2(y,Math.hypot(x,z)),fov:75};}
async function capture(id,pose){await action('investigation_view',pose);await delay(180);const receipt=await action('investigation_capture',{output:`${out}/${id}.png`});await save(`${id}-capture`,{pose,receipt});const bytes=await readFile(`${out}/${id}.png`);assert(bytes.readUInt32BE(16)===1920&&bytes.readUInt32BE(20)===1080);}
await exec(process.execPath,['tools/maps/prebuilt/build.mjs','--check'],{cwd:process.cwd(),windowsHide:true,timeout:120000});
const source=(await exec('git',['rev-parse','HEAD'],{cwd:project,windowsHide:true})).stdout.trim();if(!process.env.CAPTURE_RESUME)await save('batch-source',{source,startedUtc:new Date().toISOString()});
await save(process.env.CAPTURE_PROOF_SUFFIX?`peers-before-${process.env.CAPTURE_PROOF_SUFFIX}`:process.env.CAPTURE_RESUME?'peers-before-resume':'peers-before',await cli('game','ps','--all'));await save(process.env.CAPTURE_PROOF_SUFFIX?`launch-${process.env.CAPTURE_PROOF_SUFFIX}`:process.env.CAPTURE_RESUME?'launch-resume':'launch',await cli('game','run','--project',project,'--instance',instance,'--session',session,'--scene','res://artifacts/prop-review/audit.tscn','--fixture','roguelite','--inspect','--allow-actions','--offscreen','--offscreen-size','1920x1080'));
try{
 let state;const deadline=Date.now()+240000;
 do{await delay(1000);try{state=(await cli('runtime','inspect','--project',project,'--instance',instance,'--store-only')).store;}catch{continue;}if(state?.loadoutPickOpen)await action('loadout_pick_confirm');if(Date.now()>deadline)throw Error('Native arena not ready');}while(!state?.snapshot?.players?.some(p=>p.id===state.localPeerId)||state.loadoutPickOpen);
 await action('pause',{open:false});await action('debug_console',{invincible:true,killEnemies:true,freeFly:true,hideMinimap:true,open:false});await action('photo_mode',{active:true});await action('pause',{open:true});await delay(1200);
 const locations=(await action('investigation_prop_locations')).result;await save('prop-locations',locations);
 const entries=locations.props.flatMap(p=>p.instances.map(i=>({...i,path:p.path})));const nearest=regex=>entries.filter(p=>regex.test(p.path)).sort((a,b)=>(a.center[0]+402)**2+(a.center[2]+390)**2-((b.center[0]+402)**2+(b.center[2]+390)**2))[0];
 const roof=nearest(/roof.*hvac|roof.*unit|roof.*condenser/i);
 const horizonViews=JSON.parse(await readFile('tools/maps/study/concept-inputs/horizon-eye-views.json','utf8')).views;
 const skyline=horizonViews.find(v=>v.id==='05-street');
 const views=[{id:'street-01-outdoor',position:[-402,-15.582,-392],yaw:0,pitch:0,fov:75},{id:'street-02-fronts-doors',position:[-405,-15.58,-363],yaw:0,pitch:0,fov:75},roof?look('street-03-roof-parapets',roof.center,[4,2.5,5]):{id:'street-03-roof-parapets',position:[-402,4,-392],yaw:0,pitch:-.25,fov:75},{id:'street-04-bridge-covered',position:[-542.946,-15.774,-361.28],yaw:-1.5708,pitch:0,fov:75},look('street-05-pier-water-edge',[-499.9,-16.5,-489.4],[4,2,7]),{...skyline,id:'street-06-skyline',fov:75}];
 await save('street-views',views);await action('batch_stage',{name:'hide',payload:{}});
 for(const view of views){if(process.env.CAPTURE_RESUME){try{await access(`${out}/${view.id}.png`);continue;}catch{}}await capture(view.id,view);await save(`${view.id}-inventory`,(await action('investigation_inventory')).result);console.log(view.id,'captured');}
 const catalog=JSON.parse(await readFile('artifacts/prop-review/catalog.json','utf8'));const sheets=[],excluded=[];
 for(let index=0;index<catalog.length;index++){
  const asset=catalog[index];if(process.env.CAPTURE_NATIVE_ONLY&&!asset.native){sheets.push(asset);continue;}if(process.env.CAPTURE_RESUME&&!process.env.CAPTURE_NATIVE_ONLY){try{await access(`${out}/asset-${asset.id}.json`);sheets.push(asset);continue;}catch{}}const stage=(await action('batch_stage',{name:'asset',payload:asset})).result;if(!stage.accepted&&asset.ground){excluded.push({asset,reason:stage.error});continue;}assert(stage.accepted,JSON.stringify(stage));assert(stage.materials.length&&stage.materials.every(m=>m.class==="ShaderMaterial"&&m.grain?.material_texture_enabled===true),`Missing layered production material: ${asset.id} ${JSON.stringify(stage.materials)}`);await delay(350);
  const radius=Math.max(...stage.size,0.4);const poses=[];
  for(const [range,multiplier] of [['close',0.65],['mid',1.8],['far',5]]){const pose=look(`${asset.id}-${range}`,stage.center,offset(stage,radius,multiplier));await capture(`asset-${asset.id}-${range}`,pose);poses.push({range,pose});}
  await save(`asset-${asset.id}`,{asset,stage,poses});sheets.push(asset);
  if((index+1)%10===0)console.log(`${index+1}/${catalog.length} assets captured; no per-asset audit loop`);
 }
 const paths=[{id:'legacy-bench-close',path:'res://assets/maps/environment_detail/bench.glb.bin',kind:'static'},{id:'legacy-bin-close',path:'res://assets/maps/environment_detail/litter-bin.glb.bin',kind:'static'},{id:'cordon-apron-close',native:'*_Apron',radius:1.5,kind:'static'},{id:'soil-close',soil:'western',kind:'static'}];
 if(process.env.DEFER_MOTION){await save(process.env.CAPTURE_NATIVE_ONLY?'motion-ready-native':'motion-ready',{utc:new Date().toISOString()});while(true){try{await access(`${out}/${process.env.CAPTURE_NATIVE_ONLY?'motion-go-native':'motion-go'}.json`);break;}catch{await delay(250);}}}
 for(const path of paths){if(process.env.CAPTURE_NATIVE_ONLY&&!path.native)continue;if(process.env.CAPTURE_FOCUS==='magazine'&&!path.id.startsWith('magazine'))continue;let stage,pose,radius;if(path.street){await action('batch_stage',{name:'hide',payload:{}});stage={accepted:true,size:[4,4,4],center:path.street.position};pose=path.street;radius=4;}else{stage=(await action('batch_stage',{name:'asset',payload:path})).result;assert(stage.accepted,JSON.stringify(stage));radius=Math.max(...stage.size,.4);pose=look(path.id,stage.center,offset(stage,radius,1.05));}await action('investigation_view',pose);await action('batch_stage',{name:'animate',payload:{kind:path.kind}});await delay(1200);const folder=`${out}/tour-${path.id}`;await action('investigation_motion',{output:folder,seconds:3,amplitude:Math.min(radius*.1,.35),yaw_swing:.012});const deadline=Date.now()+30000;while(true){try{await access(`${folder}/receipt.json`);break;}catch{if(Date.now()>deadline)throw Error('Motion recording timeout');await delay(300);}}await save(`${path.id}-stage`,{path,stage,pose});console.log(path.id,'native tour recorded');}
 await save('motion-paths',paths);
 await save('asset-manifest',sheets);await save('excluded-assets',excluded);await save('logs',await cli('game','logs','--project',project,'--instance',instance));console.log(`CAPTURE PASS COMPLETE: ${sheets.length} asset sheets, six street views, four native world/material tour sections`);
}finally{await save(process.env.CAPTURE_PROOF_SUFFIX?`stop-${process.env.CAPTURE_PROOF_SUFFIX}`:process.env.CAPTURE_RESUME?'stop-resume':'stop',await cli('game','stop','--project',project,'--instance',instance));}
